# Grab-bag for platform-wide secrets that don't belong to any single
# AWS-resource-owning module (unlike rds's db_password or
# domain-controller's admin/ldap-bind credentials, these aren't produced by
# or tied to a specific piece of infrastructure this repo provisions — every
# devtool across the whole cluster reads them independently).

locals {
  ssm_tags = {
    Repo      = "devtools-labs"
    Module    = "terraform/modules/devtools-secrets"
    ManagedBy = "GitOps"
  }
}

resource "aws_ssm_parameter" "admin_password" {
  name        = var.admin_password_ssm_parameter
  description = "Created by GitOps — devtools-labs Terraform (terraform/modules/devtools-secrets). Do not edit manually; changes will be reverted on the next apply. Shared initial admin password for every devtool on the platform (see devtools-provision/README.md)."
  type        = "SecureString"
  value       = var.admin_password
  tags        = local.ssm_tags
}

# Generated, not prompted — unlike admin_password (a human-chosen login
# credential), this is just an opaque shared secret between RHBK and its
# OIDC clients, so there's no reason to ask a person to invent one.
# special = false avoids characters that need escaping/encoding wherever
# this value gets passed around (env vars, curl, k8s Secrets, ...).
resource "random_password" "rhbk_oidc_client_secret" {
  length  = 40
  special = false
}

resource "aws_ssm_parameter" "rhbk_oidc_client_secret" {
  name        = var.rhbk_oidc_client_secret_ssm_parameter
  description = "Created by GitOps — devtools-labs Terraform (terraform/modules/devtools-secrets). Do not edit manually; changes will be reverted on the next apply. Shared OIDC client secret RHBK issues to every devtool that federates SSO through it (see clusters-provision/clusters/rhbk and each devtool's oidcClientSecretSsmParameter). Randomly generated by Terraform (random_password), not user-supplied."
  type        = "SecureString"
  value       = random_password.rhbk_oidc_client_secret.result
  tags        = local.ssm_tags
}
