# Grab-bag for platform-wide secrets that don't belong to any single
# AWS-resource-owning module (unlike rds's db_password or
# domain-controller's admin/ldap-bind credentials, these aren't produced by
# or tied to a specific piece of infrastructure this repo provisions — every
# devtool across the whole cluster reads them independently).

locals {
  ssm_tags = {
    Repo      = "devtools-labs"
    Module    = "terraform/modules/devtools-secrets"
    ManagedBy = "GitOps"
  }

  # Variable defaults can't call file() directly, so the fallback lives here
  # instead — empty var.cloudflare_origin_ca_root_cert (the default) means
  # "use the committed copy."
  cloudflare_origin_ca_root_cert = var.cloudflare_origin_ca_root_cert != "" ? var.cloudflare_origin_ca_root_cert : file("${path.module}/files/cloudflare-origin-ca-rsa-root.pem")
}

resource "aws_ssm_parameter" "admin_password" {
  name        = var.admin_password_ssm_parameter
  description = "Created by GitOps — devtools-labs Terraform (terraform/modules/devtools-secrets). Do not edit manually; changes will be reverted on the next apply. Shared initial admin password for every devtool on the platform (see devtools-provision/README.md)."
  type        = "SecureString"
  value       = var.admin_password
  tags        = local.ssm_tags
}

# Generated, not prompted — unlike admin_password (a human-chosen login
# credential), this is just an opaque shared secret between RHBK and its
# OIDC clients, so there's no reason to ask a person to invent one.
# special = false avoids characters that need escaping/encoding wherever
# this value gets passed around (env vars, curl, k8s Secrets, ...).
resource "random_password" "rhbk_oidc_client_secret" {
  length  = 40
  special = false
}

resource "aws_ssm_parameter" "rhbk_oidc_client_secret" {
  name        = var.rhbk_oidc_client_secret_ssm_parameter
  description = "Created by GitOps — devtools-labs Terraform (terraform/modules/devtools-secrets). Do not edit manually; changes will be reverted on the next apply. Shared OIDC client secret RHBK issues to every devtool that federates SSO through it (see clusters-provision/clusters/rhbk and each devtool's oidcClientSecretSsmParameter). Randomly generated by Terraform (random_password), not user-supplied."
  type        = "SecureString"
  value       = random_password.rhbk_oidc_client_secret.result
  tags        = local.ssm_tags
}

# Cloudflare's public Origin CA root certificate (RSA) — not a
# Terraform-managed/generated artifact like the cloudflare module's
# origin_cert_crt/key (that module owns the lifecycle of THIS zone's own
# leaf cert, issued by Cloudflare and rotatable). This is Cloudflare's own
# static root, published once and identical for every Cloudflare customer —
# https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/.
# Every devtool's JVM needs to trust it to pass TLS verification on outbound
# in-cluster calls to *.devopstashtiot.page (routed via the CoreDNS rewrite
# straight to ingress-nginx-controller, which presents a cert chaining to
# this root) — otherwise those calls fail with "PKIX path building failed"
# (hit first on RHBK/Keycloak OIDC token exchange for bitbucket/jira/
# confluence/artifactory). Published here once so every devtool's
# ExternalSecret can reference the same value instead of duplicating the PEM
# file in git across each devtools-provision chart.
resource "aws_ssm_parameter" "cloudflare_origin_ca_root_cert" {
  name        = var.cloudflare_origin_ca_root_cert_ssm_parameter
  description = "Created by GitOps — devtools-labs Terraform (terraform/modules/devtools-secrets). Do not edit manually; changes will be reverted on the next apply. Cloudflare's public Origin CA root certificate — trusted by every devtool's JVM truststore so outbound in-cluster calls to *.devopstashtiot.page pass TLS verification. Static, publicly-published by Cloudflare (not sensitive), stored as SecureString only for consistency with the sibling origin_cert_crt/key parameters."
  type        = "SecureString"
  value       = local.cloudflare_origin_ca_root_cert
  tags        = local.ssm_tags
}
