# Second, aliased provider for the cross-region DR copy destination. The
# default (unaliased) "aws" provider is auto-generated by terragrunt's root.hcl
# generate block, always pointed at il-central-1 — this one is declared
# directly here instead, since this module is invoked as a terragrunt root
# config, not as a reusable nested module needing provider injection from a
# caller.
provider "aws" {
  alias   = "dr"
  region  = var.dr_region
  profile = var.aws_profile
}
